export type ParagraphTask = {
  id: string;
  level: "Cơ bản" | "Trung cấp" | "Nâng cao";
  kind: "Nhật ký" | "Email" | "Truyện" | "Bài luận" | "Báo cáo" | "Bài báo";
  title: string;
  topic: string;
  sentences: { vi: string; en: string }[];
};

export const PARAGRAPHS: ParagraphTask[] = [
  {
    id: "busy-day", level: "Cơ bản", kind: "Nhật ký", title: "Một ngày bận rộn", topic: "Cuộc sống hằng ngày",
    sentences: [
      ["Hôm nay là một ngày bận rộn với tôi.", "Today is a busy day for me."],
      ["Tôi thức dậy lúc sáu giờ sáng.", "I wake up at six in the morning."],
      ["Tôi gấp chăn và mở cửa sổ.", "I fold my blanket and open the window."],
      ["Sau đó, tôi đánh răng và rửa mặt.", "Then I brush my teeth and wash my face."],
      ["Tôi chuẩn bị bánh mì và sữa cho bữa sáng.", "I prepare bread and milk for breakfast."],
      ["Tôi kiểm tra lịch học trước khi ra khỏi nhà.", "I check my class schedule before leaving home."],
      ["Tôi đi xe buýt đến trường.", "I take the bus to school."],
      ["Tiết học đầu tiên bắt đầu lúc tám giờ.", "The first class starts at eight o'clock."],
      ["Tôi chăm chú nghe giáo viên giảng bài.", "I listen carefully to the teacher."],
      ["Giờ nghỉ, tôi nói chuyện với vài người bạn.", "During the break, I talk with some friends."],
      ["Chúng tôi ăn trưa tại căng tin của trường.", "We have lunch in the school cafeteria."],
      ["Buổi chiều, tôi làm bài tập nhóm ở thư viện.", "In the afternoon, I do group work in the library."],
      ["Tôi trở về nhà vào khoảng năm giờ.", "I return home at around five o'clock."],
      ["Tôi giúp mẹ chuẩn bị bữa tối.", "I help my mother prepare dinner."],
      ["Cả gia đình ăn tối cùng nhau.", "The whole family has dinner together."],
      ["Sau bữa ăn, tôi rửa bát.", "After the meal, I wash the dishes."],
      ["Tôi hoàn thành bài tập về nhà trong phòng.", "I finish my homework in my room."],
      ["Tôi đi bộ trong công viên để thư giãn.", "I walk in the park to relax."],
      ["Trước khi ngủ, tôi đọc vài trang sách.", "Before going to bed, I read a few pages of a book."],
      ["Tôi cảm thấy mệt nhưng hài lòng về ngày hôm nay.", "I feel tired but satisfied with my day."],
    ].map(([vi, en]) => ({ vi, en })),
  },
  {
    id: "friendly-email", level: "Cơ bản", kind: "Email", title: "Email cho một người bạn", topic: "Giao tiếp",
    sentences: [
      ["Chào Lan, dạo này cậu có khỏe không?", "Hi Lan, how have you been lately?"],
      ["Tớ viết thư này để kể cho cậu về trường mới của mình.", "I am writing to tell you about my new school."],
      ["Trường nằm gần một công viên lớn.", "The school is near a large park."],
      ["Khuôn viên trường rất rộng và sạch sẽ.", "The school campus is very large and clean."],
      ["Lớp của tớ có ba mươi học sinh.", "There are thirty students in my class."],
      ["Các bạn cùng lớp đều rất thân thiện.", "My classmates are all very friendly."],
      ["Giáo viên luôn sẵn lòng giúp đỡ tớ.", "The teachers are always willing to help me."],
      ["Môn học yêu thích của tớ là tiếng Anh.", "My favorite subject is English."],
      ["Chúng tớ có câu lạc bộ tiếng Anh vào thứ Tư.", "We have an English club on Wednesdays."],
      ["Tớ đã tham gia câu lạc bộ vào tuần trước.", "I joined the club last week."],
      ["Mọi người cùng chơi trò chơi và luyện nói.", "Everyone plays games and practices speaking together."],
      ["Bữa trưa ở trường cũng khá ngon.", "The lunch at school is quite good too."],
      ["Tớ thường ăn cùng hai người bạn mới.", "I usually eat with two new friends."],
      ["Sau giờ học, chúng tớ đôi khi chơi cầu lông.", "After school, we sometimes play badminton."],
      ["Tớ đang dần quen với môi trường mới.", "I am gradually getting used to the new environment."],
      ["Tuy vậy, tớ vẫn nhớ trường cũ và các bạn.", "However, I still miss my old school and friends."],
      ["Cuối tuần này trường có một ngày hội.", "The school is having a festival this weekend."],
      ["Sẽ có âm nhạc, đồ ăn và nhiều trò chơi.", "There will be music, food, and many games."],
      ["Tớ hy vọng cậu có thể đến thăm.", "I hope you can come and visit."],
      ["Hãy viết thư trả lời tớ sớm nhé.", "Please write back to me soon."],
    ].map(([vi, en]) => ({ vi, en })),
  },
  {
    id: "healthy-weekend", level: "Cơ bản", kind: "Nhật ký", title: "Cuối tuần khỏe mạnh", topic: "Sức khỏe",
    sentences: [
      ["Cuối tuần trước, tôi quyết định sống lành mạnh hơn.", "Last weekend, I decided to live a healthier life."],
      ["Tôi dậy sớm thay vì ngủ nướng.", "I got up early instead of sleeping late."],
      ["Tôi uống một cốc nước ấm.", "I drank a glass of warm water."],
      ["Sau đó, tôi chạy bộ quanh hồ.", "Then I went jogging around the lake."],
      ["Không khí buổi sáng rất trong lành.", "The morning air was very fresh."],
      ["Tôi chạy trong khoảng ba mươi phút.", "I ran for about thirty minutes."],
      ["Về nhà, tôi tắm và thay quần áo.", "When I got home, I took a shower and changed my clothes."],
      ["Bữa sáng của tôi có trứng và trái cây.", "My breakfast included eggs and fruit."],
      ["Tôi không uống nước ngọt trong ngày hôm đó.", "I did not drink any soft drinks that day."],
      ["Buổi sáng, tôi dọn dẹp phòng ngủ.", "In the morning, I cleaned my bedroom."],
      ["Tôi cũng giúp bố chăm sóc khu vườn.", "I also helped my father take care of the garden."],
      ["Bữa trưa có nhiều rau xanh.", "Lunch included plenty of green vegetables."],
      ["Sau bữa trưa, tôi nghỉ ngơi một lát.", "After lunch, I rested for a while."],
      ["Buổi chiều, tôi đi bơi cùng em gái.", "In the afternoon, I went swimming with my sister."],
      ["Chúng tôi rất vui khi luyện tập cùng nhau.", "We had a great time exercising together."],
      ["Tối đó, tôi không sử dụng điện thoại quá lâu.", "That evening, I did not use my phone for too long."],
      ["Tôi đọc sách trong một giờ.", "I read a book for an hour."],
      ["Trước khi ngủ, tôi tập vài động tác kéo giãn.", "Before bed, I did some stretching exercises."],
      ["Tôi đi ngủ lúc mười giờ.", "I went to bed at ten o'clock."],
      ["Ngày hôm sau, tôi thức dậy với nhiều năng lượng.", "The next day, I woke up with plenty of energy."],
    ].map(([vi, en]) => ({ vi, en })),
  },
  {
    id: "kindness", level: "Trung cấp", kind: "Truyện", title: "Một hành động nhỏ, một tấm lòng lớn", topic: "Văn hóa & xã hội",
    sentences: [
      ["Một chiều mưa, Minh đang trên đường về nhà.", "One rainy afternoon, Minh was on his way home."],
      ["Cậu nhìn thấy một bà cụ đứng bên đường.", "He saw an elderly woman standing by the road."],
      ["Bà đang mang vài chiếc túi rất nặng.", "She was carrying several very heavy bags."],
      ["Những chiếc xe chạy qua làm nước bắn lên vỉa hè.", "Passing cars splashed water onto the pavement."],
      ["Minh dừng lại và hỏi bà có cần giúp không.", "Minh stopped and asked if she needed help."],
      ["Bà mỉm cười và cảm ơn cậu.", "She smiled and thanked him."],
      ["Minh cầm hai chiếc túi nặng nhất.", "Minh took the two heaviest bags."],
      ["Họ cùng đi về phía trạm xe buýt.", "They walked toward the bus stop together."],
      ["Trên đường đi, bà kể về gia đình mình.", "On the way, she told him about her family."],
      ["Các con của bà đều sống ở thành phố khác.", "All of her children lived in other cities."],
      ["Vì thế, bà thường phải tự đi mua sắm.", "Therefore, she often had to go shopping by herself."],
      ["Khi đến trạm, chiếc xe buýt vừa tới.", "When they reached the stop, the bus had just arrived."],
      ["Minh giúp bà mang túi lên xe.", "Minh helped her carry the bags onto the bus."],
      ["Bà muốn gửi cậu một ít tiền để cảm ơn.", "She wanted to give him some money as thanks."],
      ["Minh lịch sự từ chối lời đề nghị.", "Minh politely refused the offer."],
      ["Cậu nói rằng ai cũng nên giúp người khác khi có thể.", "He said that everyone should help others when possible."],
      ["Bà cụ xúc động trước câu trả lời đó.", "The elderly woman was touched by his answer."],
      ["Bà chúc Minh luôn gặp nhiều điều tốt đẹp.", "She wished Minh many good things in life."],
      ["Minh về nhà muộn hơn thường lệ nhưng rất vui.", "Minh arrived home later than usual but felt very happy."],
      ["Cậu nhận ra một hành động nhỏ có thể tạo nên khác biệt lớn.", "He realized that a small act could make a big difference."],
    ].map(([vi, en]) => ({ vi, en })),
  },
  {
    id: "remote-work", level: "Trung cấp", kind: "Bài luận", title: "Làm việc từ xa", topic: "Công việc",
    sentences: [
      ["Làm việc từ xa đã trở nên phổ biến trong những năm gần đây.", "Remote work has become popular in recent years."],
      ["Hình thức này mang lại cho nhân viên nhiều sự linh hoạt.", "This arrangement gives employees greater flexibility."],
      ["Họ có thể tiết kiệm thời gian đi lại mỗi ngày.", "They can save commuting time every day."],
      ["Chi phí dành cho xăng xe và bữa trưa cũng giảm xuống.", "Expenses for transport and lunch are also reduced."],
      ["Nhiều người có thêm thời gian cho gia đình.", "Many people have more time for their families."],
      ["Một không gian yên tĩnh có thể giúp họ tập trung tốt hơn.", "A quiet space can help them concentrate better."],
      ["Tuy nhiên, làm việc tại nhà cũng có một số hạn chế.", "However, working from home also has some limitations."],
      ["Một số nhân viên cảm thấy cô đơn và thiếu kết nối.", "Some employees feel lonely and disconnected."],
      ["Việc trao đổi qua tin nhắn đôi khi gây hiểu lầm.", "Communication through messages sometimes causes misunderstandings."],
      ["Các cuộc họp trực tuyến kéo dài có thể gây mệt mỏi.", "Long online meetings can be tiring."],
      ["Nhân viên cũng khó tách biệt công việc khỏi cuộc sống riêng.", "Employees may also struggle to separate work from their personal lives."],
      ["Không phải gia đình nào cũng có phòng làm việc phù hợp.", "Not every household has a suitable workspace."],
      ["Công ty cần cung cấp thiết bị và hỗ trợ kỹ thuật.", "Companies need to provide equipment and technical support."],
      ["Người quản lý nên đặt mục tiêu rõ ràng cho cả nhóm.", "Managers should set clear goals for the whole team."],
      ["Kết quả công việc quan trọng hơn số giờ trực tuyến.", "Work results are more important than the number of hours spent online."],
      ["Các buổi gặp trực tiếp vẫn cần thiết cho sự hợp tác.", "Face-to-face meetings are still necessary for collaboration."],
      ["Một mô hình kết hợp có thể giải quyết nhiều vấn đề.", "A hybrid model can solve many of these problems."],
      ["Nhân viên có thể chọn ngày làm ở nhà hoặc văn phòng.", "Employees can choose days to work at home or in the office."],
      ["Chính sách linh hoạt cần phù hợp với từng vị trí.", "Flexible policies should suit each job role."],
      ["Nếu được quản lý tốt, làm việc từ xa có lợi cho cả hai bên.", "If managed well, remote work can benefit both employers and employees."],
    ].map(([vi, en]) => ({ vi, en })),
  },
  {
    id: "study-abroad-email", level: "Trung cấp", kind: "Email", title: "Hỏi kinh nghiệm du học", topic: "Giáo dục",
    sentences: [
      ["Chào Mai, mình nghe nói bạn đang học tại Úc.", "Hi Mai, I heard that you are studying in Australia."],
      ["Mình đang cân nhắc nộp hồ sơ cho năm học tới.", "I am considering applying for the next academic year."],
      ["Vì vậy, mình muốn hỏi bạn một vài điều.", "Therefore, I would like to ask you a few questions."],
      ["Quá trình chuẩn bị hồ sơ của bạn kéo dài bao lâu?", "How long did your application process take?"],
      ["Bạn có phải tham gia bài kiểm tra tiếng Anh nào không?", "Did you have to take an English test?"],
      ["Mình cũng muốn biết chi phí sinh hoạt trung bình.", "I would also like to know the average living costs."],
      ["Việc tìm chỗ ở gần trường có khó không?", "Was it difficult to find accommodation near the university?"],
      ["Bạn sống trong ký túc xá hay thuê nhà riêng?", "Do you live in a dormitory or rent a private apartment?"],
      ["Mình hơi lo về việc thích nghi với môi trường mới.", "I am a little worried about adapting to a new environment."],
      ["Sinh viên quốc tế có nhận được nhiều hỗ trợ không?", "Do international students receive much support?"],
      ["Bạn đã kết bạn bằng cách nào trong những tuần đầu?", "How did you make friends during the first few weeks?"],
      ["Khối lượng bài tập ở đó có nặng không?", "Is the workload there demanding?"],
      ["Giảng viên có dễ trao đổi sau giờ học không?", "Are lecturers approachable after class?"],
      ["Mình muốn tìm một công việc bán thời gian.", "I would like to find a part-time job."],
      ["Sinh viên được phép làm bao nhiêu giờ mỗi tuần?", "How many hours are students allowed to work each week?"],
      ["Phương tiện công cộng trong thành phố có thuận tiện không?", "Is public transport in the city convenient?"],
      ["Bạn có lời khuyên nào về việc quản lý chi tiêu không?", "Do you have any advice on managing expenses?"],
      ["Mình rất trân trọng nếu bạn có thể chia sẻ kinh nghiệm.", "I would really appreciate it if you could share your experience."],
      ["Câu trả lời của bạn sẽ giúp mình chuẩn bị tốt hơn.", "Your answers will help me prepare better."],
      ["Cảm ơn bạn và mong sớm nhận được hồi âm.", "Thank you, and I look forward to hearing from you soon."],
    ].map(([vi, en]) => ({ vi, en })),
  },
  {
    id: "city-report", level: "Nâng cao", kind: "Báo cáo", title: "Giao thông đô thị bền vững", topic: "Môi trường",
    sentences: [
      ["Tình trạng ùn tắc đang làm giảm chất lượng sống tại các thành phố lớn.", "Traffic congestion is reducing the quality of life in major cities."],
      ["Số lượng phương tiện cá nhân tiếp tục tăng mỗi năm.", "The number of private vehicles continues to increase every year."],
      ["Điều này làm thời gian di chuyển kéo dài đáng kể.", "This significantly lengthens commuting times."],
      ["Khí thải giao thông cũng gây ô nhiễm không khí nghiêm trọng.", "Vehicle emissions also cause serious air pollution."],
      ["Tiếng ồn liên tục ảnh hưởng đến sức khỏe của cư dân.", "Constant noise affects residents' health."],
      ["Nhiều tuyến xe buýt hiện chưa đáp ứng được nhu cầu.", "Many current bus routes do not meet public demand."],
      ["Thời gian chờ lâu khiến hành khách thiếu kiên nhẫn.", "Long waiting times make passengers impatient."],
      ["Một số khu dân cư vẫn chưa có kết nối thuận tiện.", "Some residential areas still lack convenient connections."],
      ["Thành phố nên ưu tiên đầu tư vào giao thông công cộng.", "The city should prioritize investment in public transport."],
      ["Làn đường riêng có thể giúp xe buýt di chuyển nhanh hơn.", "Dedicated lanes can help buses travel faster."],
      ["Hệ thống vé tích hợp sẽ giúp việc chuyển tuyến dễ dàng.", "An integrated ticketing system would make transfers easier."],
      ["Thông tin thời gian thực cần được cung cấp tại các điểm dừng.", "Real-time information should be provided at bus stops."],
      ["Mạng lưới đường dành cho xe đạp cũng cần được mở rộng.", "The cycling network also needs to be expanded."],
      ["Vỉa hè an toàn sẽ khuyến khích người dân đi bộ.", "Safe pavements will encourage residents to walk."],
      ["Phí đỗ xe cao hơn có thể hạn chế việc dùng ô tô.", "Higher parking fees could discourage car use."],
      ["Tuy nhiên, chính sách mới cần được triển khai công bằng.", "However, new policies must be implemented fairly."],
      ["Người thu nhập thấp cần có vé giao thông được trợ giá.", "Low-income residents need subsidized transport fares."],
      ["Doanh nghiệp nên khuyến khích giờ làm việc linh hoạt.", "Businesses should encourage flexible working hours."],
      ["Kết quả của các biện pháp cần được đánh giá thường xuyên.", "The results of these measures should be evaluated regularly."],
      ["Một chiến lược dài hạn sẽ giúp thành phố phát triển bền vững.", "A long-term strategy will help the city develop sustainably."],
    ].map(([vi, en]) => ({ vi, en })),
  },
  {
    id: "technology-article", level: "Nâng cao", kind: "Bài báo", title: "Công nghệ và khả năng tập trung", topic: "Công nghệ",
    sentences: [
      ["Các nền tảng số đã thay đổi sâu sắc cách con người tiếp nhận thông tin.", "Digital platforms have profoundly changed how people consume information."],
      ["Người dùng có thể truy cập lượng nội dung khổng lồ trong vài giây.", "Users can access a vast amount of content within seconds."],
      ["Sự tiện lợi này mang lại nhiều cơ hội học tập.", "This convenience creates many learning opportunities."],
      ["Tuy nhiên, nó cũng tạo ra những thói quen đáng lo ngại.", "However, it also creates some worrying habits."],
      ["Thông báo liên tục khiến sự chú ý thường xuyên bị gián đoạn.", "Constant notifications repeatedly interrupt attention."],
      ["Nội dung ngắn khuyến khích người dùng chuyển chủ đề nhanh chóng.", "Short-form content encourages users to switch topics quickly."],
      ["Bộ não dần quen với việc tìm kiếm phần thưởng tức thì.", "The brain gradually becomes accustomed to seeking immediate rewards."],
      ["Vì vậy, những nhiệm vụ dài có thể trở nên khó chịu hơn.", "As a result, longer tasks may become more frustrating."],
      ["Học sinh đôi khi kiểm tra điện thoại trong lúc học.", "Students sometimes check their phones while studying."],
      ["Thói quen này làm giảm chất lượng ghi nhớ.", "This habit reduces the quality of memory retention."],
      ["Làm nhiều việc cùng lúc thường không hiệu quả như mọi người nghĩ.", "Multitasking is often less effective than people believe."],
      ["Mỗi lần chuyển việc, não cần thời gian để tập trung lại.", "Each task switch requires the brain to refocus."],
      ["Người dùng nên tắt các thông báo không cần thiết.", "Users should disable unnecessary notifications."],
      ["Điện thoại có thể được đặt ngoài tầm tay khi làm việc.", "Phones can be placed out of reach while working."],
      ["Chia thời gian thành các phiên tập trung cũng rất hữu ích.", "Dividing time into focused sessions is also useful."],
      ["Những khoảng nghỉ ngắn giúp duy trì năng lượng tinh thần.", "Short breaks help maintain mental energy."],
      ["Đọc sách giấy có thể rèn luyện sự tập trung lâu dài.", "Reading printed books can train sustained attention."],
      ["Gia đình và nhà trường nên dạy kỹ năng sử dụng công nghệ.", "Families and schools should teach responsible technology use."],
      ["Mục tiêu không phải là loại bỏ hoàn toàn thiết bị số.", "The goal is not to eliminate digital devices entirely."],
      ["Điều quan trọng là xây dựng mối quan hệ cân bằng với công nghệ.", "What matters is building a balanced relationship with technology."],
    ].map(([vi, en]) => ({ vi, en })),
  },
  {
    id: "education-equality", level: "Nâng cao", kind: "Bài luận", title: "Thu hẹp khoảng cách giáo dục", topic: "Giáo dục",
    sentences: [
      ["Giáo dục chất lượng là nền tảng của một xã hội công bằng.", "Quality education is the foundation of an equitable society."],
      ["Tuy nhiên, cơ hội học tập vẫn được phân bố không đồng đều.", "However, learning opportunities remain unevenly distributed."],
      ["Học sinh ở vùng nông thôn thường thiếu giáo viên có kinh nghiệm.", "Students in rural areas often lack experienced teachers."],
      ["Nhiều trường không có phòng thí nghiệm hoặc thư viện phù hợp.", "Many schools do not have adequate laboratories or libraries."],
      ["Khoảng cách số khiến vấn đề trở nên nghiêm trọng hơn.", "The digital divide makes the problem more serious."],
      ["Một số gia đình không đủ khả năng mua máy tính.", "Some families cannot afford computers."],
      ["Kết nối mạng không ổn định cản trở việc học trực tuyến.", "Unreliable internet connections hinder online learning."],
      ["Khó khăn tài chính còn buộc nhiều học sinh nghỉ học sớm.", "Financial hardship also forces many students to leave school early."],
      ["Chính phủ cần phân bổ ngân sách dựa trên nhu cầu thực tế.", "Governments need to allocate funding based on actual needs."],
      ["Các khu vực khó khăn nên nhận được nhiều nguồn lực hơn.", "Disadvantaged areas should receive more resources."],
      ["Học bổng có thể giúp học sinh tiếp tục việc học.", "Scholarships can help students continue their education."],
      ["Giáo viên cần được khuyến khích làm việc tại vùng xa.", "Teachers should be encouraged to work in remote areas."],
      ["Các chương trình đào tạo cần hỗ trợ họ phát triển chuyên môn.", "Training programs need to support their professional development."],
      ["Công nghệ có thể mở rộng khả năng tiếp cận bài giảng tốt.", "Technology can expand access to high-quality lessons."],
      ["Tuy nhiên, thiết bị chỉ hữu ích khi được sử dụng đúng cách.", "However, devices are useful only when used properly."],
      ["Phụ huynh cũng cần được hướng dẫn để hỗ trợ con em.", "Parents also need guidance to support their children."],
      ["Doanh nghiệp có thể đóng góp thiết bị và chương trình cố vấn.", "Businesses can contribute equipment and mentoring programs."],
      ["Kết quả giáo dục cần được theo dõi bằng dữ liệu minh bạch.", "Educational outcomes should be monitored through transparent data."],
      ["Không một giải pháp đơn lẻ nào có thể xóa bỏ khoảng cách.", "No single solution can eliminate the gap."],
      ["Sự hợp tác lâu dài sẽ mang lại cơ hội thực sự cho mọi trẻ em.", "Long-term cooperation will create genuine opportunities for every child."],
    ].map(([vi, en]) => ({ vi, en })),
  },
];
